### ISSUE TITLE
Đổi tên các folder con trong folder môn học

### ISSUE THREAD

**Issue by thu4n** [SVUIT/scripts#3]
Đổi tên các folder K16, K17, K18 thành các học kỳ + năm học mà tài liệu của môn đó được submit. 

Tức là nếu tài liệu của môn học ví dụ là Nhập môn mạng được submit vào HK2 NH2023-2024 thì nó sẽ vô folder HK2 NH2023-2024, không quan tâm là của khóa nào submit.

**Comment by ghost** [comment]
Done Done Done nha anh Thuận oi.

**Comment by thu4n** [comment]
Làm tốt lắm em trai
